-- Users and their login sessions.
--
-- Sessions live in the database rather than in a signed cookie because a row
-- can be deleted: logging out, or revoking every session after a password
-- change, is a DELETE. A JWT cannot be un-issued — you can only wait for it to
-- expire. See ADR-007.

create table users (
    id            bigint generated always as identity primary key,
    email         text        not null,
    password_hash text        not null,
    created_at    timestamptz not null default now(),

    -- Case-insensitive uniqueness. Without this, Bob@x.com and bob@x.com are
    -- two accounts and the second login attempt is a mystery to the user.
    constraint users_email_unique unique (email),
    constraint users_email_lowercase check (email = lower(email)),
    constraint users_email_shaped   check (email like '%_@_%._%')
);

create table sessions (
    -- The session id is the secret sent in the cookie, so it is generated by
    -- the application from a CSPRNG, not by the database from a sequence.
    -- A guessable session id is an account takeover.
    id         text        primary key,
    user_id    bigint      not null references users (id) on delete cascade,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null,

    constraint sessions_expire_after_creation check (expires_at > created_at)
);

-- Every request looks up a session by id (the primary key, already indexed).
-- This index serves the other direction: revoking all of one user's sessions.
create index sessions_user_id_idx on sessions (user_id);
